---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Namespace }}-tgbotserver-service
  labels:
    app: {{ $.Release.Namespace }}-tgbotserver
spec:
  selector:
    app: {{ $.Release.Namespace }}-tgbotserver
  type: ClusterIP
  ports:
    - port: 80
