---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tgbotserver
  labels:
    app: tgbotserver
spec:
  selector:
    matchLabels:
      app: tgbotserver
  template:
    metadata:
      name: tgbotserver
      labels:
        app: tgbotserver
    spec:
      containers:
        - name: tgbotserver
          imagePullPolicy: IfNotPresent
          image: "{{ $.Values.ImageNameTgBotServer }}:{{ $.Values.ImageTagTgBotServer }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: tgbotserver

